title: "Annica Gehlen"
description: "Economist | PhD Candidate"
url: "https://amageh.github.io"  # Update with your GitHub Pages URL
baseurl: ""  # Leave empty if deploying to root

# Al-Folio theme
remote_theme: alshedivat/al-folio

# Author info
author:
  name: "Annica Gehlen"
  bio: "Economist | PhD Candidate"
  location: "Berlin, Germany"
  email: "agehlen@diw.de"
  github: "amageh"
  linke
