title: "Annica Gehlen"
description: "Researcher Website"
baseurl: "" 
url: "https://youramagehusername.github.io"

remote_theme: BlackrockDigital/startbootstrap-clean-blog-jekyll

plugins:
  - jekyll-feed
  - jekyll-seo-tag

plugins:
  - jekyll-feed
  - jekyll-seo-tag

author:
  name: "Annica Gehlen"
  bio: "Economist | PhD Candidate"
  location: "Berlin, Germany"

social:
  github: https://github.com/amageh
  linkedin: https://www.linkedin.com/in/annica-gehlen-13b24a137
  email: agehlen@diw.de
  bluesky: https://amageh.bsky.social

# Navigation links
navigation:
  - text: "Home"
    url: "/"
  - text: "Research"
    url: "/research/"
  - text: "CV"
    url: "/cv/"