title: "Annica Gehlen"
description: "Economist | PhD Candidate"
baseurl: "" 
url: "https://amageh.github.io"

theme: null  # disables remote_theme so we can use our own layout

author:
  name: "Annica Gehlen"
  bio: "Economist | PhD Candidate"
  location: "Berlin, Germany"

social:
  github: "https://github.com/amageh"
  linkedin: "https://www.linkedin.com/in/annica-gehlen-13b24a137"
  email: "agehlen@diw.de"
  bluesky: "https://amageh.bsky.social"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
